"""Generate the source-code payload used by the static course website."""

from __future__ import annotations

import json
from pathlib import Path


SOURCE_FILES = (
    "shared.py",
    "synchronous_crawlers.py",
    "async_crawler.py",
    "compare_examples.py",
    "lessons/lesson_timeout.py",
    "lessons/lesson_retry.py",
    "lessons/lesson_semaphore.py",
    "lessons/lesson_cancellation.py",
)

OUTPUT_PATH = Path("docs/assets/source-files.js")


def build_payload() -> dict[str, str]:
    """Read source files and return the browser payload."""
    return {
        source_path: Path(source_path).read_text(encoding="utf-8")
        for source_path in SOURCE_FILES
    }


def render_javascript(payload: dict[str, str]) -> str:
    """Serialize source files as a deterministic global JavaScript object."""
    serialized_payload = json.dumps(payload, ensure_ascii=False, indent=2)
    return (
        "// Generated by scripts/generate_site_sources.py. Do not edit by hand.\n"
        f"window.CRAWLER_SOURCE_FILES = {serialized_payload};\n"
    )


def main() -> int:
    """Write the generated source-code payload."""
    OUTPUT_PATH.write_text(
        render_javascript(build_payload()),
        encoding="utf-8",
    )
    print(f"Generated {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
